### ISSUE TITLE
Package Checks Fail

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#12]
There are some errors when "Checking" package that I don't fully understand (or have time to chase down).

**Comment by AugustT** [comment]
Really don't worry about this. `Check` is something we only want to run when we are close to a v1.0 It will be very demoralizing to look at it before then!

**Comment by drnickisaac** [comment]
so close until we are closer to v1 or leave open??

**Comment by AugustT** [comment]
Closing this for now
