### ISSUE TITLE
Allow read .fst

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#25]
We planning to switch sparta outputs from .rData to .fst. See here: [https://github.com/BiologicalRecordsCentre/sparta/issues/202](url)

So wrappeR needs to become flexible enough to recognise both file formats and read in the data accordingly.

**Comment by drnickisaac** [comment]
We can already read `.rds` so it should be easy to generalise this code (at lines 86-89 of `tempSampPost.R`).
NB There is a statement that defines the `filetype` on line 26 of `applySamp.R`

**Comment by 03rcooke** [comment]
I think we should stick with R's native .rds filetypes where possible, see here: http://svmiller.com/blog/2020/02/comparing-qs-fst-rds-for-bigger-datasets/

"First, a relational database (i.e. SQL) provides the absolute fastest read times even if the object sizes of these relational databases are as large as raw text (i.e. they have no file compression). Second, serialization through [the {fst} package](https://www.fstpackage.org/) provides the second fastest load time but the file size that emerges from this serialization is discernibly larger than another serialization processes native to R. Further, serialization through : discards variable/value label information that may come in the data set. Third, serialization in R (i.e. readRDS()) is a best of both worlds, of a sort. The load time is slower than what a researcher would get through a relational database or serialization via {fst}, but the file size is the absolute smallest, the load time is not too slow relative to other options, and an R serialized data frame retains variable/value label information."
