### ISSUE TITLE
Missing dragonfly models 2020_bds

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#30]
The 2020_bds models are missing from the object store. If you look at `list.files("/data-s3/occmods/Dragonflies/occmod_outputs/2020_bds")` it only returns 5 JASMIN models for the first species. 

These are important now that the `createRoster `default is "most_recent" for models

**Comment by mlogie** [comment]
Thanks for tagging me @03rcooke I will submit these for upload tomorrow

**Comment by robboyd** [comment]
@03rcooke can you remember which files gave errors when loaded in from the object store? Think it was some hoverflies and a couple of species from one other group? Would be great if you could re-upload these @mlogie

**Comment by drnickisaac** [comment]
@robboyd  https://github.com/BiologicalRecordsCentre/wrappeR/issues/19

**Comment by 03rcooke** [comment]
There's also a missing model for one of the bees: "/data-s3/occmods/Bees/occmod_outputs/2020_bwars/Bombus humilis_20000_3.rdata" is missing, _1 and _2 are present.

I can't remember what the problem with the hoverflies was, will look now.

**Comment by 03rcooke** [comment]
I think the problem was with Charlie's hoverfly models, @mlogie hoverfly models work!

FungusGnats crashes `cannot open compressed file '/data-s3/occmods/FungusGnats/occmod_outputs/2017_Charlie/Platyura marginata.rdata', probable reason 'No such file or directory'Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection`

**Comment by 03rcooke** [comment]
LeafSeedBeatles also fails with `Error in load(fileName) : empty (zero-byte) input file` after `"Col_5768 571"`

**Comment by mlogie** [comment]
Working on uploads now.  Hoverflies should now be done (or at least is processing, should be in within the hour).
FungusGnats and LSB loading up on the PC end now - probably won't be ready for upload until Monday morning @robboyd @03rcooke

**Comment by robboyd** [comment]
Excellent thanks Mark

**Comment by mlogie** [comment]
I'm just going to upload everything in those two groups, overwriting old files

**Comment by 03rcooke** [comment]
Thanks Mark!!

**Comment by mlogie** [comment]
Hoverflies complete.  FungusGnats ongoing (there was a hardware bug that caused an issue)

**Comment by 03rcooke** [comment]
Thanks for the update on progress @mlogie 

`Spiders/occmod/outputs/2019_marlog` also look strange to me. I don't know spiders that well, but there's only 181 species with models and there only go from A - D alphabetically which seems strange to me.

**Comment by mlogie** [comment]
gah - that command line approach was supposed to be robust, but looks like it was flaky.
LSBeetles are in. FungusGnats are in.  Hoverflies are in.  Spiders I'll investigate

**Comment by 03rcooke** [comment]
@AugustT asked for an update on object store model issues. Here is the current information:

- **Bees**
- 2020_bwars - one file missing "Bombus humilis_20000_3"
- **Dragonflies**
- 2017_Charlie - Error in if (nRec >= minObs) { : argument is of length zero
- 2020_bds - after Aeshna cyanea, Error in load(fileName) : error reading from connection
- **Hoverflies**
- 2017_Charlie - after Platycheirus peltatus Error in load(fileName) : empty (zero-byte) input file
- 2017_update works but no input data (species names differ to 2017_Charlie input data)
- **LeafSeedBeetles**
- 2017_Charlie - after Col_5768, Error in load(fileName) : empty (zero-byte) input file
- 2019_Jack - after Col_1289, Error in sample.int(length(x), size, replace, prob) : cannot take a sample larger than the population when 'replace = FALSE'
- **Moths**
- 2017_Charlie - multiple files missing
- **Spiders**
- 2019_marlog after Acartauchenius scurrilis, Error in if (nRec >= minObs) { : argument is of length zero

**Comment by 03rcooke** [comment]
With @drnickisaac fixes hopefully we can now just focus on model uploads for those missing models, rather than those that have crashed (I will check this), but that would just mean the missing bee model, and the lots of missing moth models.

**Comment by 03rcooke** [comment]
@mlogie here is the info about the model issues

**Comment by 03rcooke** [comment]
Dragonflies are now working

**Comment by mlogie** [comment]
@03rcooke I've been steadily downloading the dragonfly models.  Are you now saying that the model files there are fine and I don't need to load these up?

**Comment by 03rcooke** [comment]
@mlogie yes! The extra checks that Nick put in means these models are now working! Moths and the one bee file are the priorities, I will re-check the rest of the issues I listed above with the new checks.

**Comment by mlogie** [comment]
@03rcooke I've set off the moths uploading.  They should be piling in the object store now.  The original files I uploaded appear to have been from an earlier run, but I found the final data stored elsewhere.  So it's not surprising these were never complete.  It's 50,000+ files, so it's going to take a while to upload, but it's doing it automatically, so it'll just chug away until it gets there.
Regarding that bee file - I can't find that file on JASMIN.  I honestly don't know why.  It's possible it was never produced and not picked up as missing when I ran restart_failures.  Every other file is there (afaik).  I'll see if I can find it elsewhere, but can't think of a solution here if I can't short of running the full models again.

**Comment by mlogie** [comment]
It's done 2000 in about an hour and a half, so all being well all the moths will be there in about a day and a half

**Comment by drnickisaac** [comment]
Glad to hear this is making progress.
FWIW we don't actually need to keep all the moth files: we only need the first and last daisy from each species' chain. Could this save time/space?

**Comment by AugustT** [comment]
I think that for completeness it would be wise to have all the files up there. Since the process is automated I doubt there would be a big time saving.

**Comment by 03rcooke** [comment]
As far as I'm away all models are on the object store. Open a new issue if anyone notices missing models
