### ISSUE TITLE
applyFilters filters based on number of observations at the species level not the region level

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#32]
As far as I can tell the filtering of species in `applyFilters` is based on the number of observations (e.g., 50) at the species level (i.e., GB/UK), as `tempSampPost `seems to get the number of observations from the model metadata. Therefore the metadata in `tempSampPost `named `meta `is species specific but not region specific.

Was this the intended behaviour @robboyd @GPowney? Would it possible to filter based on the number of observations at the region level. E.g. filter to species with 50 records in England?

**Comment by drnickisaac** [comment]
I recall both @GPowney  and @robboyd talking about a criterion of 50 records within the country. But the code doesn't seem to implement this at the Region scale. In fact, all of the metadata is for the global dataset, not the specific region in question. It'd be really helpful to know if this was the intention, and whether an older version ever implemented this at region-scale.

**Comment by AugustT** [comment]
@robboyd @GPowney any comments on this?

**Comment by 03rcooke** [comment]
I think the current consensus on this is that we need to make it more clear in the code/vignette that the analyses currently test if a species has the minimum required observations at the global level (i.e., GB or UK) not the regional level. This is important for communicating the results of the analyses.

Future steps include generating regional-level metadata in `sparta`

**Comment by AugustT** [comment]
Maybe if the threshold is used, and regions are used, you could run ´message("Note: threshold is applied at the global level, not within regions")´

**Comment by 03rcooke** [comment]
I've now added a `scaleObs` argument to `createRoster` this allows you to apply the observation threshold at either the "global" scale (i.e., all observations for a species) or at the region scale (i.e., all observations within a region for a species). I think this makes it much more explicit.

**Comment by AugustT** [comment]
@03rcooke To really make this explicit you should not provide a default, that forces the user to make an explicit choice about the scale, rather then sleep-walking into using the 'global' default
