### ISSUE TITLE
calcMSI for bma method is not log or logit transforming occupancy

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#33]
Within `calcMSI`, for the bma method, the means and sds are calculated from raw occupancy rather than loge or logit occupancy which is required for `BRCindicator::bma`

**Comment by robboyd** [comment]
I'd speak to @drnickisaac about this as there was some discussion over how to best transform occupancy

**Comment by 03rcooke** [comment]
Ah okay, thanks @robboyd!

**Comment by drnickisaac** [comment]
Most of our applications we will use log(Occupancy), so this should be the default (not logit). So this should be implemented as standard for `calcMSI`. A "nice to have" would be to build in the option of logit into wrappeR. However, this is not essential: users who really want the logit option can implement directly in `bma`.
