### ISSUE TITLE
Which species to drop based on Charlie's notes?

### ISSUE THREAD

**Issue by robboyd** [BiologicalRecordsCentre/wrappeR#35]
@drnickisaac I have included Charlie's list of species to be excluded in wrappeR. In Charlie's list species may be dropped for a number of reasons, e.g. scheme advice, more specific species available for aggregates, etc. One criteria for exclusion is simply "didn't meet criteria". I assume this means didn't meet data criteria for inclusion, e.g. number of records or gaps in data etc. So I ignored this filter and retain species flagged as "didn't meet criteria", because these species are removed anyway further down the pipeline. Is this ok?

**Comment by drnickisaac** [comment]
"I assume this means didn't meet data criteria for inclusion, e.g. number of records or gaps in data etc"
I don't know but it should be easy to test by cross-referencing. e.g. how many species in that category (should be between 2000 and 7000 total).

**Comment by 03rcooke** [comment]
From a quick check they seem to be species excluded due to <50 observations. There's 5,232 species listed under the "Didn't meet criteria" category and I checked 10 species, all of which had <50 obs.

**Comment by drnickisaac** [comment]
Good - that's fairly clear. So I think that means that the answer to @robboyd 's question is Yes.

**Comment by drnickisaac** [comment]
I think this issue can be closed. I suggest you keep it for the sprint so that 1) you can confer in person on the day and 2) get an easy win towards the milestone.
