### ISSUE TITLE
Accommodate either .rdata or .rds files

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#39]
The new Trichoptera models are saved as .rds files (Trichoptera/occmod_outputs/2021_Ellcur) - wrappeR needs to become flexible enough to recognise both file formats and read in the data accordingly.

**Comment by drnickisaac** [comment]
I think I have done this on my local version.

**Comment by AugustT** [comment]
Should this be closed @drnickisaac ?

**Comment by drnickisaac** [comment]
Issue can be closed once @03rcooke  has had a chance to review my Pull Request and agrees I have indeed fixed the problem.

**Comment by AugustT** [comment]
@03rcooke check close if complete

**Comment by AugustT** [comment]
ensure this is not case sensitive
