### ISSUE TITLE
Don't need to sample from posterior for newest models

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#40]
For the new models, e.g., Trichoptera/2021_Ellcur, we only have 999 posterior samples so there's no need to run `tempSampPost` I think, so we could bypass this step somehow?

This also means that we should now set the maximum allowed for `nSamps = 999`, else the code breaks for the new models

**Comment by drnickisaac** [comment]
I think I've dealt with this, at lest on @EllieDyer's fork.

**Comment by 03rcooke** [comment]
`#following 4 lines added by ED(NJBI)
      if(sample_n < nrow(raw_occ)){
        raw_occ <- raw_occ[sample(1:nrow(raw_occ), sample_n),]
      }else{
        sample_n <- nrow(raw_occ)} # raw_occ does not get sampled but revised sample_n is used later`

These are the lines added to Ellie's fork. They make sense but I'm worried they could lead to confusing outputs. For example if you ran `applyFilters()` to a set of models of 2017_Charlie and a set of models for 2021_Ellcur with `nSamps = 2000`, it would return 2000 posterior samples for the 2017_Charlie models but 999 posterior samples for the 2021_Ellcur models (if it could return this).

Perhaps we just constrain nSamps to be a maximum of 999 instead?

**Comment by drnickisaac** [comment]
In my fork I've added a check to ensure that the number of iterations in the model is at least as high as the `sample_n`. This should overcome the problem. However, I also added a tolerance, meaning that wrappeR would not throw a wobbly if  `sample_n=1000` when the number of samples is 999. We will need to revisit the implications of that later.

**Comment by AugustT** [comment]
@03rcooke check if fixed

**Comment by 03rcooke** [comment]
Looks fixed to me, will reopen if any problems come up 

@EllieDyer this is likely one that will break for your analysis if it is going to break
