### ISSUE TITLE
Need an ability to skip species in tempSampPost()

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#42]
There are several reasons why `tempSampPost()` should not attempt to run this line:
`raw_occ <- data.frame(out$BUGSoutput$sims.list[REGION_IN_Q])`

The most pressing is that sparta does not estimate occupancy in regions where the species has zero records. So there needs to be a check, such as:
`REGION_IN_Q %in% mod$regions`

Another related reason is that I made a controversial and possibly unwelcome change in sparta 0.2.09. I added some code to calculate the rules of thumb metrics: if the species falls short then sparta does not run a model, but it does save a file containing only metadata. @mlogie @AugustT may feel this is stupid, but it should be straightforward to skip species by testing for the existence of a model object:
`!is.null(mod$model)`

**Comment by drnickisaac** [comment]
I have fixed this in my local version.

**Comment by drnickisaac** [comment]
There are more general classes of problem that we might want to anticipate. For example, the occupancy model file might be corrupted or have zero content. So there should be some extra checks that the model file contains everything we would expect it to.

**Comment by 03rcooke** [comment]
I think the `!is.null(out_dat$model)` check should catch most of these. More might come up in the future but can be added then
