### ISSUE TITLE
spp.list in tempSampPost looks redundant

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#45]
I think the species list arising from `spp.list` at line 32-35 in `tempSampPost()` should be identical to `keep`.
If so it would speed thing up to delete, since calls to `list.files()` are time-consuming.

**Comment by 03rcooke** [comment]
I've now modified `tempSampPost` to pass `keep` (unique species names) and `keep_iter` (species names with iteration numbers if applicable) from `applyFilters` to prevent costly calls to `list.files`
