### ISSUE TITLE
Upload meta data creation script to wrapper

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/wrappeR#50]
Upload meta data creation script to wrapper @mlogie

**Comment by AugustT** [comment]
@mlogie Can you pop this up for Francesca

**Comment by mlogie** [comment]
Yep, doing that now @FrancescaMancini @AugustT

**Comment by AugustT** [comment]
@mlogie - can we have a chat on Zoom about this?

**Comment by AugustT** [comment]
It seems that this does not easily allow @FrancescaMancini to access the file level data. Perhaps @FrancescaMancini and @mlogie can have a follow up chat on this. Part of the problem is the variation in the subfolder structure.

**Comment by AugustT** [comment]
This issue is close
