### ISSUE TITLE
applyFilters fails for JASMIN groups

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#6]
The groups where we've used JASMIN & daisy-chaining have a different structure. At present, the code in `applyFilters` can't handle this.

**Comment by 03rcooke** [comment]
@drnickisaac @AugustT 

I'm currently trying to adapt `applyFilters ` and therefore `tempSampPost` to work with the JASMIN daisy chained outputs. I can happily extract the metadata from the initial model e.g. 

`load(paste0(indata, species, "_2000_1.rdata")) # where metadata is stored for JASMIN models
nRec <- out$species_observations`
 
However I'm struggling to work out how the occupancy data is stored in the JASMIN outputs. For example Charlie's models store it like this:

`load(paste0(indata, species, ".rdata"))
raw_occ <- data.frame(out$BUGSoutput$sims.list[REGION_IN_Q])`

This gives a dataframe with 10,002 rows and 47 columns (years), however each of the final-daisy JASMIN chains (e.g., 20000_1, 20000_2, 20000_3) gives a dataframe with 666 rows and 50 columns (years)

So is it correct for the JASMIN models to just bind the three dataframes together from the three chains (e.g., 20000_1, 20000_2, 20000_3) even though this will only produce a dataframe with 1998 rows? Or do I need to bind dataframes together for all the chains (e.g., _1, _2, _3) and all the daisies (e.g., 2000:20000)?

**Comment by AugustT** [comment]
You basically have the right idea. You can bind together those last elements of each chain and use that data. If you need more you will have to go back to an earlier element of the chain. I have code that does this in my group workspace on Jasmin, I think it is in the master scripts folder and is called combine chains or similar.

**Comment by AugustT** [comment]
You tell it where the chains are and how many samples you want and it will combine as many of the chain elements as it needs, starting at the end and working back

**Comment by 03rcooke** [comment]
Ah okay, thanks!

**Comment by drnickisaac** [comment]
@03rcooke You only need the final daisy in the chain. The earlier ones have not, in theory, reached convergence. And also, if the final daisy has 1998 iterations (across chains) then it's more than enough to provide a dataset from which `wrappeR` can sample 1000 of them.

**Comment by 03rcooke** [comment]
I've made it accommodate all the more recent JASMIN models, which are consistent with _2000_1 having the metadata and _20000_1 etc having the converged estimates.

However I hadn't spotted that the moths, lichens etc also have JASMIN models but very inconsistently numbered. I can't work out how these are structured. So for the the first moth for instance the models go:
Lep_1501_1000_1.rdata, ..._1000_2.rdata, ..._1000_3.rdata, ..._2000_2.rdata, ..._2000_3.rdata, ..._3000_2.rdata, ..._3000_3.rdata, ..._4000_2.rdata, ..._4000_3.rdata, ..._5000_2.rdata, ..._5000_3.rdata, ..._6000_3.rdata

So the key points are not all species have the same maximum number of iterations, here we have 6000, plus some of the chains seem to be dropped on the way through, e.g. there is _2 and _3 for 5000 but only _3 for 6000. Any ideas on how best to use these for the `applyFilters` function. I.e., how best to get 1,000 estimates from these models?

@AugustT @drnickisaac

**Comment by AugustT** [comment]
@03rcooke This looks like an incomplete run. Are you sure that these are the final model versions? I remember that some species had to be re-run and were in a separate re-run folder. However, I'm pretty sure we created a folder with all the final models in it. What you describe here would be hard to use since you need all three chains to detect convergence issues

**Comment by 03rcooke** [comment]
Ah okay, I thought it was a different model structure, but it looks like the moth models didn't upload to the object store correctly. @mlogie would you be able to have a look at this? Else I heard that the models are also on a shared drive, do either of you know where they are located?
