### ISSUE TITLE
tempSampPost won't read from region_aggs

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#61]
We added a series of tests to ensure that `tempSampPost()` does not attempt to read in data that does not exist. At present this is too strict: if we specify a region name from the `region_aggs` then it fails.

**Comment by 03rcooke** [comment]
I'm not quite sure I understand this, as it must only happen for the newer models. Is it that the models have regional occupancy estimates but those regions aren't listed in `region_aggs`? We can easily change the check so it looks for the actual regional occupancy data rather than the `region_aggs` slot

**Comment by drnickisaac** [comment]
@03rcooke you may be right that this is no longer a problem. I am thinking of the three criteria for reading the contents of the model file, one of which is to check whether the region in question was modelled. I notice you've updated the code since I introduced it:
https://github.com/BiologicalRecordsCentre/wrappeR/blob/610648254fddf0ac8be04a73c8330ebbc7870388/R/tempSampPost.R#L124
The old version was something like:
`REGION_IN_Q %in% paste0("psi.fs.r_", out_dat$regions)`
which would have returned `FALSE` if `REGION_IN_Q` were among `region_aggs`. I've not tried your new version (I'm having problems with git), so you'll have to assess whether your new code is foolproof.

**Comment by drnickisaac** [comment]
Also, please check the behaviour when asking wrappeR to extract the global (i.e. UK) occupancy. In the model this is simply `psi.fs`. The help text on `createRoster()` suggests one should set 'region = "UK"` rather than leave it blank. But how does that play out when applying the test at line 124, above?

**Comment by drnickisaac** [comment]
We really need to ensure this is working ASAP: Louise and @FrancescaMancini  will be relying on this for the UKBI 2021.

**Comment by drnickisaac** [comment]
This seems to be fixed now. I have successfully extracted the "ENG" region aggregate from Francesca's newest bee model runs.
