### ISSUE TITLE
extractMetadata fails due to inconsistent file names on the object store

### ISSUE THREAD

**Issue by FrancescaMancini** [BiologicalRecordsCentre/wrappeR#64]
The number of species in the data and the number of species modeled is sometimes extracted incorrectly.

1. Some folders have more than one file as input data (e.g. Charlie's Bryophytes input data). This results in no data being loaded and the number of species as NA
2. Model output files are named inconsistently, the number of species modeled is not always correct.

**Comment by DylanCarbone** [comment]
extractMetadata no longer exists so I'm closing this. Please let me know if this was a mistake and I will re open the issue.
