### ISSUE TITLE
Inconsistency in reading model$data()

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#74]
in combineSamps() there are *two* occasions when the data is read directly from the model. This is inconsistent and inefficient. I think it also brings a bug.

On line 52 we have `dat <- out_meta$model$data()`. If there are regions, then `dat` is then subsetted on line 79 to include only those rows within the region under consideration. 

Then again on line 167:
      `dat <- out_meta$model$data()`
`dat` is then used to calculate the metadata data frame `out2`, but without subsetting to the region under consideration.

I think this means that the data on gaps etc is currently global, not regional as we believed it to be.

**Comment by 03rcooke** [comment]
I have attempted to fix this in my current fork, will test out and then merge when it's working
