### ISSUE TITLE
Ability to specify `indata` in `applySamp`

### ISSUE THREAD

**Issue by drnickisaac** [BiologicalRecordsCentre/wrappeR#83]
I'm trying to call `applySamp()` directly to work with some sparta output not stored on objectStore. I realise that `indata` is hard-coded according to the format used on the ObjectStore, with "occmod_outputs" and version folders inside the taxon folder. This is a problem. I am working on Datalabs, which won't allow me to use underscores in the folder name. Solution would be to allow users to tell `applySamp()` where the data are stored.

**Comment by DylanCarbone** [comment]
Hi @drnickisaac, Datalabs does (at least now) allow underscores to be included in file paths. But I think that the createRoster() function should not be hard code the model output paths so it can access model outputs outside of the object store.

**Comment by DylanCarbone** [comment]
see #81
