### ISSUE TITLE
Use of `most_recent` functionality

### ISSUE THREAD

**Issue by 03rcooke** [BiologicalRecordsCentre/wrappeR#85]
After a meeting today (Kath, Rob C, Francesca, Martin), we think that it'd be better to use a combination of `most_recent` and a new permission column in the metadata spreadsheet (currently unnamed) to automatically select the most suitable versions of the occupancy models across the taxonomic groups. Currently in the `createRoster` function we use `most_recent` to select the newest occupancy models for each group based on the metadata spreadsheet, however some models, such as the LERC models, should not be reused and so should be excluded from this selection. The idea is to change functionality so that it selects the `most_recent` models where permission is not known to be refused (i.e., seek permission but likely to be granted).

**Comment by FrancescaMancini** [comment]
We can close this as the plan has changed a bit and I have opened two new issues to describe what is left to do.
